"""empty message

Revision ID: 9f63910c0b20
Revises: 9f84b2fcb39b
Create Date: 2020-09-13 07:26:02.181609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f63910c0b20'
down_revision = '9f84b2fcb39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('channel_icon_url', sa.String(length=128), nullable=True))
    op.add_column('user_account', sa.Column('channel_url', sa.String(length=128), nullable=True))
    op.add_column('user_account', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('user_account', sa.Column('subscriber_count', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'video', 'user_account', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_column('user_account', 'subscriber_count')
    op.drop_column('user_account', 'name')
    op.drop_column('user_account', 'channel_url')
    op.drop_column('user_account', 'channel_icon_url')
    # ### end Alembic commands ###
